### ISSUE TITLE
ImportError: cannot import name 'Random'

### ISSUE THREAD

**Issue by cmt2001** [smilecc/24h-raspberry-live-on-bilibili#2]
报错，百度看了下
crypto装了，site-packges里面第一个字母改成大写了，无效
后来说这个是在pycrypto里面，但是官方网站说这个库根本没有python3.6版本
那么怎么让它跑起来呢

**Comment by cmt2001** [comment]
解决
https://blog.csdn.net/a624806998/article/details/78596543
这个，环境变量修改一下就可以编译通过了
虽然现在又卡在winrandom了

**Comment by cmt2001** [comment]
果然没法在win运行吗
MEDIA SERVICE 报错，/resource/music为空
但是并没有尝试调用NETEASTMUSIC.py下载音乐，就一直报错....

**Comment by smilecc** [comment]
在Win下无法直接运行 因为ffmpeg的参数是arm平台的
