### ISSUE TITLE
容器里运行blive错误

### ISSUE THREAD

**Issue by mhcms** [smilecc/24h-raspberry-live-on-bilibili#20]
./blive: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./blive)

**Comment by smilecc** [comment]
用的是项目中的Dockerfile吗，可以在容器里面看下GLIBC的版本：
```bash
$ strings /lib/x86_64-linux-gnu/libc.so.6 | grep GLIBC
```

没有的2.28的话，网上找教程编译一个2.28的glibc。
