### ISSUE TITLE
运行main.py时提示 [Media Service][ERROR] can't sync to MPEG frame

### ISSUE THREAD

**Issue by pachi-qwq** [smilecc/24h-raspberry-live-on-bilibili#4]
![image](https://user-images.githubusercontent.com/20966488/44100262-41395bc4-a017-11e8-97c3-b44c8ce40e7b.png)

**Comment by smilecc** [comment]
一运行就提示这个吗？

**Comment by pachi-qwq** [comment]
是的是的，不过后来我发现这是因为music的目录里面有flac格式的音乐，替换成MP3格式的之后就没这个错误了。但是再次运行main.py却提示“Permission denied”。我是在我的云服务器上面运行的，系统是Arch x64 , X264以及ffmpeg都是直接用pacman安装的，不知道是否是因为这个？？
![image](https://user-images.githubusercontent.com/20966488/44210811-096d6580-a19a-11e8-96fc-c81544233e43.png)

另外可否拿个联系方式？tg？

**Comment by pachi-qwq** [comment]
是的，详细说明已在issues上啦。
Can <notifications@github.com<mailto:notifications@github.com>> 于 2018年8月16日周四 21:04写道：

一运行就提示这个吗？

**Comment by smilecc** [comment]
看起来是`./log/ffmpeg.log`没有写入权限，尝试一下
```bash
$ chmod 777 ./log/ffmpeg.log
```

**Comment by pachi-qwq** [comment]
测试了一下，没加777权限前，ffmpeg里面是有内容的。
我截取了里面的一段：



ffmpeg version n4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.1.1 (GCC) 20180531
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, image2, from './resource/img/darksouls.jpg':
  Duration: 00:00:00.33, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 1920x1080 [SAR 1:1 DAR 16:9], 3 fps, 3 tbr, 3 tbn, 3 tbc
[mp3 @ 0x55786b5dbd00] Estimating duration from bitrate, this may be inaccurate
Input #1, mp3, from './resource/music/withme.mp3':
  Metadata:
    track           : 11
    title           : With Me
    artist          : Sum 41
    album           : All the Good Shit: 14 Solid Gold Hits, 2001-2008
    genre           : 朋克/新浪潮【Punk&New Wave Music】
    comment         : 163 key(Don't modify):6YURAByiRHQ6CI5tvtxzQg==
    date            : 2009
  Duration: 00:04:50.38, start: 0.000000, bitrate: 320 kb/s
    Stream #1:0: Audio: mp3, 44100 Hz, stereo, fltp, 320 kb/s
Codec AVOption crf (Select the quality for constant quality mode) specified for output file #0 (rtmp://live-send.acg.tv/livelive_597174_1502522?streamname=live_597174_1502522&key=d78125ad74b985583938ba4d4d8ce400) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Codec AVOption preset (Configuration preset) specified for output file #0 (rtmp://live-send.acg.tv/livelive_597174_1502522?streamname=live_597174_1502522&key=d78125ad74b985583938ba4d4d8ce400) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
**[rtmp @ 0x55786b600100] Server error: Failed to publish 
rtmp://live-send.acg.tv/livelive_597174_1502522?streamname=live_597174_1502522&key=d78125ad74b985583938ba4d4d8ce400: Operation not permitted**



log里面都是这一段东西。

此外，config里面的cookie是填小号的还是大号的呢？
话说，tg搜索不到你的id，233.刚想起，现在+86的手机号不能私聊了，联系方式就罢了吧~

**Comment by smilecc** [comment]
你确认这个rtmp地址是可用的吗？因为我看到我bilibili的推流地址是`rtmp://qn.live-send.acg.tv/live-qn/`为开头的，当然也有可能是不同用户的不一样。
可以尝试用OBS向这个地址推流试一下。

cookie的话大号小号都可以，我个人建议用小号。

**Comment by pachi-qwq** [comment]
是的，推流地址可以在obs上使用。

Can <notifications@github.com<mailto:notifications@github.com>> 于 2018年8月16日周四 22:06写道：

你确认这个rtmp地址是可用的吗？因为我看到我bilibili的推流地址是rtmp://qn.live-send.acg.tv/live-qn/<http://qn.live-send.acg.tv/live-qn/>为开头的，当然也有可能是不同用户的不一样。
可以尝试用OBS向这个地址推流试一下。

cookie的话大号小号都可以，我个人建议用小号。
