### ISSUE TITLE
无法点播音乐，查看后台提示找不到音乐，是不是网易云的网址需要更换了

### ISSUE THREAD

**Issue by tlj218** [smilecc/24h-raspberry-live-on-bilibili#6]

**Comment by a1bireo** [comment]
试了一下，添加cookie就好了
https://blog.csdn.net/sergiojune/article/details/81561481

> 这下好了，装逼失败，被网易云认出来我是爬虫的，那我试试加下请求头?结果加了还是一个样，这个也算是个巨坑吧。解决方法还是加请求头，只需要加两个，一个是浏览器识别 user-agent ,另一个是 cookie ，想不到吧？我也想不到，居然还有在cookie上面做反爬的，但是我用了 session 来保持cookie还是不行，需要自己复制浏览的cookie就行保存才可以。

--------------------------------------------------
补充，确实有些api更换了，可以参考 [网易云音乐命令行版本](https://github.com/darknessomi/musicbox/blob/master/NEMbox/api.py)
