### ISSUE TITLE
那个运行main.py之后报错了

### ISSUE THREAD

**Issue by very-handsome-boy** [smilecc/24h-raspberry-live-on-bilibili#7]
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from utit.Log import Log
ImportError: No module named utit.Log
这个怎么解决呀，蟹蟹啦

**Comment by smilecc** [comment]
这个util.Log就是从 https://github.com/smilecc/blive-raspberry/blob/master/util/Log.py 中import进来的，如果找不到的话，可能是代码不完整

**Comment by very-handsome-boy** [comment]
蟹蟹楼主，那个问题应该是我自己用python2运行导致的但是今天报了另外一个错

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from util.Log import Log
  File "/home/pi/new/blive-raspberry/util/Log.py", line 2, in <module>
    from colorlog import ColoredFormatter
ImportError: No module named 'colorlog'
这个是我没配置好还是，找不到文件了，怎么解决呀

**Comment by smilecc** [comment]
```bash
pip3 install colorlog
```

**Comment by very-handsome-boy** [comment]
蟹蟹楼主啦
